var data = [{"headTitle":"Drag and drop flowchart",
"direction":"Directions:",
"directionTextBegin":"From the bottom panel, drag each label into its correct position on the graphic. To start over, click \"Reset.\" To view the graphic again, click \"View Graphic.\"",
"foootNote":"footer",
"popupShow":"\"Congratulations, you successfully completed the graphic\"",
"drop_area_id":["1","2","3","4","5","6","7","8","9"],
"action":"create_activity",
"CorrectOptionArray":["1","2","3","4","5","6","7","8","9"],
"OptionArray":[1,2,3,4,5,6,7,8,9],
"ariaLabel":['Ground','Ocean, marine organisms, and ocean sediments','Aquatic organisms and fresh water','Agricultural soil','Food plants','Humans','Animals','Target pest','Crops and livestock'],
"biganImg":"images/begin.png",
"background_img":"images/blank.png",
"blank_width":1332,
"blank_height":419,
"drop_images":["images/drop_1.png","images/drop_2.png","images/drop_3.png","images/drop_4.png","images/drop_5.png","images/drop_6.png","images/drop_7.png","images/drop_8.png","images/drop_9.png"],
"drop_width":"50",
"drop_height":"30",
"drag_images":["images/drag_1.png","images/drag_2.png","images/drag_3.png","images/drag_4.png","images/drag_5.png","images/drag_6.png","images/drag_7.png","images/drag_8.png","images/drag_9.png"],
"drag_width":131,
"drag_height":65,
"dropx":[165,157,140,139,233,445,457,446,407],
"dropy":[139,185,260,306,412,137,224,288,432]}]